use_exif_size: no
flann_algorithm: KDTREE
feature_process_size: 2048
feature_min_frames: 8000
processes: 4
matching_gps_neighbors: 8
matching_gps_distance: 0
depthmap_method: PATCH_MATCH
depthmap_resolution: 640
depthmap_min_patch_sd: 1
depthmap_min_consistent_views: 3
optimize_camera_parameters: yes
undistorted_image_format: tif
bundle_outlier_filtering_type: AUTO
align_orientation_prior: vertical
triangulation_type: ROBUST
bundle_common_position_constraints: no
feature_type: SIFT
use_altitude_tag: yes
align_method: auto
local_bundle_radius: 0
submodels_relpath: ../submodels/opensfm
submodel_relpath_template: ../submodels/submodel_%04d/opensfm
submodel_images_relpath_template: ../submodels/submodel_%04d/images
submodel_size: 8
submodel_overlap: 10.0