align_method: auto
align_orientation_prior: vertical
bundle_common_position_constraints: false
bundle_outlier_filtering_type: AUTO
depthmap_method: PATCH_MATCH
depthmap_min_consistent_views: 3
depthmap_min_patch_sd: 1
depthmap_resolution: 640
feature_min_frames: 8000
feature_process_size: 2048
feature_type: SIFT
flann_algorithm: KDTREE
local_bundle_radius: 0
matching_gps_distance: 0
matching_gps_neighbors: 8
optimize_camera_parameters: true
processes: 4
submodel_images_relpath_template: ../submodels/submodel_%04d/images
submodel_overlap: 10.0
submodel_relpath_template: ../submodels/submodel_%04d/opensfm
submodel_size: 8
submodels_relpath: ../submodels/opensfm
triangulation_type: ROBUST
undistorted_image_format: tif
undistorted_image_max_size: 640
use_altitude_tag: true
use_exif_size: false
